// ignore_for_file: file_names

import 'package:music_notes/music_notes.dart';

Map<int, List<dynamic>> problemListCMajor =
{
  // 문제번호 / 음표위치 / 정답  [-4,7,10,14]
  1:[[Note.e.sharp.inOctave(4)
  ,Note.c.inOctave(4)
  ,Note.g.inOctave(3)
  ,Note.c.inOctave(3)]
  ,[100.0,'I','','']
  ,'C'
  ,Note.c.major
  ],
  2:[[Note.c.inOctave(5)
    ,Note.g.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.e.inOctave(3)]
    ,[100.0,'I','6','',]
    ,'C/E'
    ,Note.c.major
  ],
  3:[[Note.e.inOctave(5)
    ,Note.g.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.g.inOctave(3)]
    ,[100.0,'I','4','6',]
    ,'C/G'
    ,Note.c.major],
  4:[[Note.a.inOctave(4)
    ,Note.f.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.d.inOctave(3)]
    ,[100.0,'ii','','',]
    ,'Dm'
    ,Note.c.major],
  5:[[Note.d.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.f.inOctave(3)]
    ,[100.0,'ii','6','',]
    ,'Dm/F'
    ,Note.c.major],
  6:[[Note.d.inOctave(5)
    ,Note.f.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.a.inOctave(3)]
    ,[100.0,'ii','4','6',]
    ,'Dm/A'
    ,Note.c.major],
  7:[[Note.b.inOctave(4)
    ,Note.g.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.e.inOctave(3)]
    ,[100.0,'iii','','',]
    ,'Em'
    ,Note.c.major],
  8:[[Note.b.inOctave(4)
    ,Note.g.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.g.inOctave(3)]
    ,[100.0,'iii','6','',]
    ,'Em/G'
    ,Note.c.major],
  9:[[Note.b.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.g.inOctave(3)
    ,Note.b.inOctave(2)]
    ,[100.0,'iii','4','6',]
    ,'Em/B'
    ,Note.c.major],
  10:[[Note.f.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.f.inOctave(2)]
    ,[100.0,'IV','','',]
    ,'F'
    ,Note.c.major],
  11:[[Note.c.inOctave(4)
    ,Note.f.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.a.inOctave(3)]
    ,[100.0,'IV','6','',]
    ,'F/A'
    ,Note.c.major],
  12:[[Note.f.inOctave(5)
    ,Note.a.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.c.inOctave(3)]
    ,[100.0,'IV','4','6',]
    ,'F/C'
    ,Note.c.major],
  13:[[Note.b.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.g.inOctave(3)
    ,Note.g.inOctave(2)]
    ,[100.0,'V','','',]
    ,'G'
    ,Note.c.major],
  14:[[Note.b.inOctave(4)
    ,Note.g.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.b.inOctave(2)]
    ,[100.0,'V','6','',]
    ,'G/B'
    ,Note.c.major],
  15:[[Note.g.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.d.inOctave(3)]
    ,[100.0,'V','4','6',]
    ,'G/D'
    ,Note.c.major],
  16:[[Note.a.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.e.inOctave(3)
    ,Note.a.inOctave(2)]
    ,[100.0,'vi','','',]
    ,'Am'
    ,Note.c.major],
  17:[[Note.e.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.c.inOctave(3)]
    ,[100.0,'vi','6','',]
    ,'Am/C'
    ,Note.c.major],
  18:[[Note.c.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.e.inOctave(2)]
    ,[100.0,'vi','4','6',]
    ,'Am/E'
    ,Note.c.major],
  19:[[Note.d.inOctave(4)
    ,Note.f.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.b.inOctave(2)]
    ,[100.0,'vii','','',]
    ,'Bm(5b)'
    ,Note.c.major],
  20:[[Note.d.inOctave(4)
    ,Note.b.inOctave(4)
    ,Note.f.inOctave(3)
    ,Note.d.inOctave(3)]
    ,[100.0,'vii','6','',]
    ,'Bm(5b)/D'
    ,Note.c.major],
  21:[[Note.d.inOctave(5)
    ,Note.d.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.f.inOctave(3)]
    ,[100.0,'vii','4','6',]
    ,'Bm(5b)/F'
    ,Note.c.major],
};

Map<int, List<dynamic>> problemListGMajor =
{
  // 문제번호 / 음표위치 / 정답  [-4,7,10,14]
  22:[[Note.b.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.g.inOctave(3)
    ,Note.g.inOctave(2)]
    ,[100.0,'I','','',]
    ,'G'
    ,Note.g.major],
  23:[[Note.g.inOctave(5)
    ,Note.g.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.b.inOctave(2)]
    ,[100.0,'I','6','',]
    ,'G/B'
    ,Note.g.major],
  24:[[Note.d.inOctave(5)
    ,Note.g.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.d.inOctave(3)]
    ,[100.0,'I','4','6',]
    ,'G/D'
    ,Note.g.major],
  25:[[Note.a.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.e.inOctave(3)
    ,Note.a.inOctave(2)]
    ,[100.0,'ii','','',]
    ,'Am'
    ,Note.g.major],
  26:[[Note.a.inOctave(5)
    ,Note.a.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.c.inOctave(3)]
    ,[100.0,'ii','6','',]
    ,'Am/C'
    ,Note.g.major],
  27:[[Note.a.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.e.inOctave(2)]
    ,[100.0,'ii','4','6',]
    ,'Am/E'
    ,Note.g.major],
  28:[[Note.b.inOctave(4)
    ,Note.f.sharp.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.b.inOctave(2)]
    ,[100.0,'iii','','',]
    ,'Bm'
    ,Note.g.major],
  29:[[Note.b.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.f.sharp.inOctave(3)
    ,Note.d.inOctave(3)]
    ,[100.0,'iii','6','',]
    ,'Bm/D'
    ,Note.g.major],
  30:[[Note.b.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.f.sharp.inOctave(2)]
    ,[100.0,'iii','4','6',]
    ,'Bm/F#'
    ,Note.g.major],
  31:[[Note.c.inOctave(5)
    ,Note.g.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.c.inOctave(3)]
    ,[100.0,'IV','','',]
    ,'C'
    ,Note.g.major],
  32:[[Note.c.inOctave(5)
    ,Note.g.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.e.inOctave(3)]
    ,[100.0,'IV','6','',]
    ,'C/E'
    ,Note.g.major],
  33:[[Note.e.inOctave(5)
    ,Note.g.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.g.inOctave(3)]
    ,[100.0,'IV','4','6',]
    ,'C/G'
    ,Note.g.major],
  34:[[Note.d.inOctave(5)
    ,Note.f.sharp.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.d.inOctave(2)]
    ,[100.0,'V','','',]
    ,'D'
    ,Note.g.major],
  35:[[Note.d.inOctave(5)
    ,Note.a.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.f.sharp.inOctave(2)]
    ,[100.0,'V','6','',]
    ,'D/F#'
    ,Note.g.major],
  36:[[Note.d.inOctave(5)
    ,Note.f.sharp.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.a.inOctave(2)]
    ,[100.0,'V','4','6',]
    ,'D/A'
    ,Note.g.major],
  37:[[Note.e.inOctave(5)
    ,Note.g.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.e.inOctave(2)]
    ,[100.0,'vi','','',]
    ,'Em'
    ,Note.g.major],
  38:[[Note.g.inOctave(5)
    ,Note.b.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.g.inOctave(2)]
    ,[100.0,'vi','6','',]
    ,'Em/G'
    ,Note.g.major],
  39:[[Note.e.inOctave(5)
    ,Note.g.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.b.inOctave(2)]
    ,[100.0,'vi','4','6',]
    ,'Em/B'
    ,Note.g.major],
  40:[[Note.a.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.f.sharp.inOctave(2)]
    ,[100.0,'vii','','',]
    ,'F#m(5b)'
    ,Note.g.major],
  41:[[Note.f.sharp.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.a.inOctave(2)]
    ,[100.0,'vii','6','',]
    ,'F#m(5b)/A'
    ,Note.g.major],
  42:[[Note.a.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.f.sharp.inOctave(3)
    ,Note.c.inOctave(3)]
    ,[100.0,'vii','4','6',]
    ,'F#m(5b)/C'
    ,Note.g.major],
};

Map<int, List<dynamic>> problemListDMajor =
{
  // 문제번호 / 음표위치 / 정답  [-4,7,10,14]
  43:[[Note.f.sharp.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.d.inOctave(2)]
    ,[100.0,'I','','',]
    ,'D'
    ,Note.d.major],
  44:[[Note.a.inOctave(5)
    ,Note.a.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.f.sharp.inOctave(2)]
    ,[100.0,'I','6','',]
    ,'D/F#'
    ,Note.d.major],
  45:[[Note.a.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.f.sharp.inOctave(3)
    ,Note.a.inOctave(2)]
    ,[100.0,'I','4','6',]
    ,'D/A'
    ,Note.d.major],
  46:[[Note.b.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.g.inOctave(3)
    ,Note.e.inOctave(3)]
    ,[100.0,'ii','','',]
    ,'Em'
    ,Note.d.major],
  47:[[Note.e.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.g.inOctave(3)
    ,Note.g.inOctave(2)]
    ,[100.0,'ii','6','',]
    ,'Em/G'
    ,Note.d.major],
  48:[[Note.b.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.g.inOctave(3)
    ,Note.b.inOctave(2)]
    ,[100.0,'ii','4','6',]
    ,'Em/B'
    ,Note.d.major],
  49:[[Note.a.inOctave(5)
    ,Note.a.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(3)]
    ,[100.0,'iii','','',]
    ,'F#m'
    ,Note.d.major],
  50:[[Note.a.inOctave(4)
    ,Note.f.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.a.inOctave(3)]
    ,[100.0,'iii','6','',]
    ,'F#m/A'
    ,Note.d.major],
  51:[[Note.f.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'iii','4','6',]
    ,'F#m/C#'
    ,Note.d.major],
  52:[[Note.d.inOctave(4)
    ,Note.b.inOctave(4)
    ,Note.d.inOctave(3)
    ,Note.g.inOctave(2)]
    ,[100.0,'IV','','',]
    ,'G'
    ,Note.d.major],
  53:[[Note.g.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.g.inOctave(3)
    ,Note.b.inOctave(2)]
    ,[100.0,'IV','6','',]
    ,'G/B'
    ,Note.d.major],
  54:[[Note.b.inOctave(4)
    ,Note.g.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.d.inOctave(3)]
    ,[100.0,'IV','4','6',]
    ,'G/D'
    ,Note.d.major],
  55:[[Note.a.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.e.inOctave(3)
    ,Note.a.inOctave(2)]
    ,[100.0,'V','','',]
    ,'A'
    ,Note.d.major],
  56:[[Note.a.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'V','6','',]
    ,'A/C#'
    ,Note.d.major],
  57:[[Note.a.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.e.inOctave(3)
    ,Note.e.inOctave(2)]
    ,[100.0,'V','4','6',]
    ,'A/E'
    ,Note.d.major],
  58:[[Note.b.inOctave(4)
    ,Note.f.sharp.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.b.inOctave(3)]
    ,[100.0,'vi','','',]
    ,'Bm'
    ,Note.d.major],
  59:[[Note.d.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.f.sharp.inOctave(3)
    ,Note.d.inOctave(3)]
    ,[100.0,'vi','6','',]
    ,'Bm/D'
    ,Note.d.major],
  60:[[Note.b.inOctave(5)
    ,Note.b.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.f.sharp.inOctave(3)]
    ,[100.0,'vi','4','6',]
    ,'Bm/F#'
    ,Note.d.major],
  61:[[Note.e.inOctave(4)
    ,Note.g.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'vii','','',]
    ,'C#m(5b)'
    ,Note.d.major],
  62:[[Note.g.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.e.inOctave(3)
    ,Note.e.inOctave(2)]
    ,[100.0,'vii','6','',]
    ,'C#m(5b)/E'
    ,Note.d.major],
  63:[[Note.e.inOctave(5)
    ,Note.c.sharp.inOctave(5)
    ,Note.e.inOctave(4)
    ,Note.g.inOctave(3)]
    ,[100.0,'vii','4','6',]
    ,'C#m(5b)/G'
    ,Note.d.major],
};

Map<int, List<dynamic>> problemListAMajor =
{
  // 문제번호 / 음표위치 / 정답  [-4,7,10,14]
  64:[[Note.c.sharp.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.e.inOctave(3)
    ,Note.a.inOctave(2)]
    ,[100.0,'I','','',]
    ,'A'
    ,Note.a.major],
  65:[[Note.e.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'I','6','',]
    ,'A/C#'
    ,Note.a.major],
  66:[[Note.c.sharp.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.e.inOctave(2)]
    ,[100.0,'I','4','6',]
    ,'A/E'
    ,Note.a.major],
  67:[[Note.d.inOctave(4)
    ,Note.b.inOctave(4)
    ,Note.f.sharp.inOctave(3)
    ,Note.b.inOctave(2)]
    ,[100.0,'ii','','',]
    ,'Bm'
    ,Note.a.major],
  68:[[Note.d.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.f.sharp.inOctave(3)
    ,Note.d.inOctave(2)]
    ,[100.0,'ii','6','',]
    ,'Bm/D'
    ,Note.a.major],
  69:[[Note.d.inOctave(4)
    ,Note.b.inOctave(4)
    ,Note.f.sharp.inOctave(3)
    ,Note.f.sharp.inOctave(2)]
    ,[100.0,'ii','4','6',]
    ,'Bm/F#'
    ,Note.a.major],
  70:[[Note.c.sharp.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.g.sharp.inOctave(3)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'iii','','',]
    ,'C#m'
    ,Note.a.major],
  71:[[Note.g.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.c.sharp.inOctave(3)
    ,Note.e.inOctave(3)]
    ,[100.0,'iii','6','',]
    ,'C#m/E'
    ,Note.a.major],
  72:[[Note.c.sharp.inOctave(5)
    ,Note.e.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(2)]
    ,[100.0,'iii','4','6',]
    ,'C#m/G'
    ,Note.a.major],
  73:[[Note.f.sharp.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.d.inOctave(3)]
    ,[100.0,'IV','','',]
    ,'D'
    ,Note.a.major],
  74:[[Note.d.inOctave(5)
    ,Note.a.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.f.sharp.inOctave(3)]
    ,[100.0,'IV','6','',]
    ,'D/F#'
    ,Note.a.major],
  75:[[Note.f.sharp.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.a.inOctave(3)]
    ,[100.0,'IV','4','6',]
    ,'D/A'
    ,Note.a.major],
  76:[[Note.e.inOctave(4)
    ,Note.g.sharp.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.e.inOctave(2)]
    ,[100.0,'V','','',]
    ,'E'
    ,Note.a.major],
  77:[[Note.e.inOctave(5)
    ,Note.b.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.g.sharp.inOctave(2)]
    ,[100.0,'V','6','',]
    ,'E/G#'
    ,Note.a.major],
  78:[[Note.g.sharp.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.e.inOctave(3)
    ,Note.b.inOctave(2)]
    ,[100.0,'V','4','6',]
    ,'E/B'
    ,Note.a.major],
  79:[[Note.c.sharp.inOctave(5)
    ,Note.a.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.f.sharp.inOctave(2)]
    ,[100.0,'vi','','',]
    ,'F#m'
    ,Note.a.major],
  80:[[Note.f.sharp.inOctave(5)
    ,Note.a.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.a.inOctave(2)]
    ,[100.0,'vi','6','',]
    ,'F#m/A'
    ,Note.a.major],
  81:[[Note.f.sharp.inOctave(5)
    ,Note.a.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'vi','4','6',]
    ,'F#m/C#'
    ,Note.a.major],
  82:[[Note.b.inOctave(5)
    ,Note.b.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.g.sharp.inOctave(2)]
    ,[100.0,'vii','','',]
    ,'G#m(5b)'
    ,Note.a.major],
  83:[[Note.b.inOctave(4)
    ,Note.g.sharp.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.b.inOctave(2)]
    ,[100.0,'vii','6','',]
    ,'G#m(5b)/B'
    ,Note.a.major],
  84:[[Note.g.sharp.inOctave(5)
    ,Note.b.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.d.inOctave(3)]
    ,[100.0,'vii','4','6',]
    ,'G#m(5b)/D'
    ,Note.a.major],
};

Map<int, List<dynamic>> problemListEMajor =
{
  // 문제번호 / 음표위치 / 정답  [-4,7,10,14]
  85:[[Note.e.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.g.sharp.inOctave(3)
    ,Note.e.inOctave(3)]
    ,[100.0,'I','','',]
    ,'E'
    ,Note.e.major],
  86:[[Note.e.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.b.inOctave(3)
    ,Note.g.sharp.inOctave(3)]
    ,[100.0,'I','6','',]
    ,'E/G#'
    ,Note.e.major],
  87:[[Note.e.inOctave(5)
    ,Note.g.sharp.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.b.inOctave(3)]
    ,[100.0,'I','4','6',]
    ,'E/B'
    ,Note.e.major],
  88:[[Note.c.sharp.inOctave(5)
    ,Note.f.sharp.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.f.sharp.inOctave(3)]
    ,[100.0,'ii','','',]
    ,'F#m'
    ,Note.e.major],
  89:[[Note.c.sharp.inOctave(5)
    ,Note.f.sharp.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.a.inOctave(2)]
    ,[100.0,'ii','6','',]
    ,'F#m/A'
    ,Note.e.major],
  90:[[Note.f.sharp.inOctave(5)
    ,Note.a.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'ii','4','6',]
    ,'F#m/C'
    ,Note.e.major],
  91:[[Note.b.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.g.sharp.inOctave(3)
    ,Note.g.sharp.inOctave(2)]
    ,[100.0,'iii','','',]
    ,'G#m'
    ,Note.e.major],
  92:[[Note.b.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.g.sharp.inOctave(3)
    ,Note.b.inOctave(2)]
    ,[100.0,'iii','6','',]
    ,'G#m/B'
    ,Note.e.major],
  93:[[Note.b.inOctave(4)
    ,Note.g.sharp.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.d.inOctave(2)]
    ,[100.0,'iii','4','6',]
    ,'G#m/D'
    ,Note.e.major],
  94:[[Note.e.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.a.inOctave(2)]
    ,[100.0,'IV','','',]
    ,'A'
    ,Note.e.major],
  95:[[Note.e.inOctave(5)
    ,Note.a.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'IV','6','',]
    ,'A/C#'
    ,Note.e.major],
  96:[[Note.e.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.e.inOctave(2)]
    ,[100.0,'IV','4','6',]
    ,'A/E'
    ,Note.e.major],
  97:[[Note.f.sharp.inOctave(4)
    ,Note.b.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.b.inOctave(2)]
    ,[100.0,'V','','',]
    ,'B'
    ,Note.e.major],
  98:[[Note.f.sharp.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.b.inOctave(3)
    ,Note.d.sharp.inOctave(3)]
    ,[100.0,'V','6','',]
    ,'B/D#'
    ,Note.e.major],
  99:[[Note.f.sharp.inOctave(5)
    ,Note.b.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(2)]
    ,[100.0,'V','4','6',]
    ,'B/F#'
    ,Note.e.major],
  100:[[Note.g.sharp.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'vi','','',]
    ,'C#m'
    ,Note.e.major],
  101:[[Note.e.inOctave(5)
    ,Note.g.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.e.inOctave(3)]
    ,[100.0,'vi','6','',]
    ,'C#m/e'
    ,Note.e.major],
  102:[[Note.g.sharp.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.g.sharp.inOctave(3)]
    ,[100.0,'vi','4','6',]
    ,'C#m/G#'
    ,Note.e.major],
  103:[[Note.f.sharp.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.f.sharp.inOctave(3)
    ,Note.d.sharp.inOctave(3)]
    ,[100.0,'vii','','',]
    ,'D#m(5b)'
    ,Note.e.major],
  104:[[Note.a.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(3)
    ,Note.f.sharp.inOctave(2)]
    ,[100.0,'vii','6','',]
    ,'D#m(5b)/F#'
    ,Note.e.major],
  105:[[Note.f.sharp.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.a.inOctave(2)]
    ,[100.0,'vii','4','6',]
    ,'D#m(5b)/A'
    ,Note.e.major],
};

Map<int, List<dynamic>> problemListBMajor =
{
  // 문제번호 / 음표위치 / 정답  [-4,7,10,14]
  106:[[Note.b.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(3)
    ,Note.b.inOctave(2)]
    ,[100.0,'I','','',]
    ,'B'
    ,Note.b.major],
  107:[[Note.b.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.f.sharp.inOctave(3)
    ,Note.d.sharp.inOctave(3)]
    ,[100.0,'I','6','',]
    ,'B/D#'
    ,Note.b.major],
  108:[[Note.b.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.f.sharp.inOctave(2)]
    ,[100.0,'I','4','6',]
    ,'B/F#'
    ,Note.b.major],
  109:[[Note.e.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(3)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'ii','','',]
    ,'C#m'
    ,Note.b.major],
  110:[[Note.g.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(3)
    ,Note.e.inOctave(3)]
    ,[100.0,'ii','6','',]
    ,'C#m/E'
    ,Note.b.major],
  111:[[Note.c.sharp.inOctave(5)
    ,Note.e.inOctave(4)
    ,Note.c.sharp.inOctave(3)
    ,Note.g.sharp.inOctave(3)]
    ,[100.0,'ii','4','6',]
    ,'C#m/G#'
    ,Note.b.major],
  112:[[Note.f.sharp.inOctave(4)
    ,Note.a.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(3)
    ,Note.d.sharp.inOctave(3)]
    ,[100.0,'iii','','',]
    ,'D#m'
    ,Note.b.major],
  113:[[Note.f.sharp.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.a.sharp.inOctave(3)
    ,Note.f.sharp.inOctave(3)]
    ,[100.0,'iii','6','',]
    ,'D#m/F#'
    ,Note.b.major],
  114:[[Note.f.sharp.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.a.sharp.inOctave(2)]
    ,[100.0,'iii','4','6',]
    ,'D#m/A#'
    ,Note.b.major],
  115:[[Note.b.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.g.sharp.inOctave(3)
    ,Note.e.inOctave(3)]
    ,[100.0,'IV','','',]
    ,'E'
    ,Note.b.major],
  116:[[Note.b.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.e.inOctave(3)
    ,Note.g.sharp.inOctave(2)]
    ,[100.0,'IV','6','',]
    ,'E/G#'
    ,Note.b.major],
  117:[[Note.g.sharp.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.b.inOctave(2)]
    ,[100.0,'IV','4','6',]
    ,'E/B'
    ,Note.b.major],
  118:[[Note.c.sharp.inOctave(4)
    ,Note.a.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(3)]
    ,[100.0,'V','','',]
    ,'F#'
    ,Note.b.major],
  119:[[Note.c.sharp.inOctave(5)
    ,Note.c.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(3)
    ,Note.a.sharp.inOctave(2)]
    ,[100.0,'V','6','',]
    ,'F#/A#'
    ,Note.b.major],
  120:[[Note.f.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.a.sharp.inOctave(3)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'V','4','6',]
    ,'F#/C#'
    ,Note.b.major],
  121:[[Note.b.inOctave(5)
    ,Note.b.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(3)]
    ,[100.0,'vi','','',]
    ,'G#m'
    ,Note.b.major],
  122:[[Note.b.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(3)
    ,Note.b.inOctave(2)]
    ,[100.0,'vi','6','',]
    ,'G#m/B'
    ,Note.b.major],
  123:[[Note.b.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.g.sharp.inOctave(3)
    ,Note.d.sharp.inOctave(2)]
    ,[100.0,'vi','4','6',]
    ,'G#m/D#'
    ,Note.b.major],
  124:[[Note.c.sharp.inOctave(5)
    ,Note.e.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.a.sharp.inOctave(3)]
    ,[100.0,'vii','','',]
    ,'A#m(5b)'
    ,Note.b.major],
  125:[[Note.a.sharp.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'vii','6','',]
    ,'A#m(5b)/C#'
    ,Note.b.major],
  126:[[Note.a.sharp.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.e.inOctave(3)]
    ,[100.0,'vii','4','6',]
    ,'A#m(5b)/E'
    ,Note.b.major],
};

Map<int, List<dynamic>> problemListFSharpMajor =
{
  // 문제번호 / 음표위치 / 정답  [-4,7,10,14]
  127:[[Note.c.sharp.inOctave(5)
    ,Note.a.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(3)]
    ,[100.0,'I','','',]
    ,'F#'
    ,Note.f.sharp.major],
  128:[[Note.c.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.a.sharp.inOctave(3)]
    ,[100.0,'I','6','',]
    ,'F#/A#'
    ,Note.f.sharp.major],
  129:[[Note.c.sharp.inOctave(5)
    ,Note.f.sharp.inOctave(4)
    ,Note.a.sharp.inOctave(3)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'I','4','6',]
    ,'F#/C#'
    ,Note.f.sharp.major],
  130:[[Note.b.inOctave(3)
    ,Note.d.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(3)
    ,Note.g.sharp.inOctave(2)]
    ,[100.0,'ii','','',]
    ,'G#m'
    ,Note.f.sharp.major],
  131:[[Note.g.sharp.inOctave(4)
    ,Note.d.sharp.inOctave(5)
    ,Note.g.sharp.inOctave(3)
    ,Note.b.inOctave(2)]
    ,[100.0,'ii','6','',]
    ,'G#m/B'
    ,Note.f.sharp.major],
  132:[[Note.b.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(3)
    ,Note.d.sharp.inOctave(3)]
    ,[100.0,'ii','4','6',]
    ,'G#m/D#'
    ,Note.f.sharp.major],
  133:[[Note.a.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.e.sharp.inOctave(3)
    ,Note.a.sharp.inOctave(2)]
    ,[100.0,'iii','','',]
    ,'A#m'
    ,Note.f.sharp.major],
  134:[[Note.e.sharp.inOctave(4)
    ,Note.a.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'iii','6','',]
    ,'A#m/C#'
    ,Note.f.sharp.major],
  135:[[Note.a.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.a.sharp.inOctave(3)
    ,Note.e.sharp.inOctave(2)]
    ,[100.0,'iii','4','6',]
    ,'A#m/E#'
    ,Note.f.sharp.major],
  136:[[Note.f.sharp.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.b.inOctave(2)]
    ,[100.0,'IV','','',]
    ,'B'
    ,Note.f.sharp.major],
  137:[[Note.f.sharp.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.f.sharp.inOctave(3)
    ,Note.d.sharp.inOctave(3)]
    ,[100.0,'IV','6','',]
    ,'B/D#'
    ,Note.f.sharp.major],
  138:[[Note.d.sharp.inOctave(5)
    ,Note.f.sharp.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.f.sharp.inOctave(2)]
    ,[100.0,'IV','4','6',]
    ,'B/F#'
    ,Note.f.sharp.major],
  139:[[Note.e.sharp.inOctave(5)
    ,Note.g.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'V','','',]
    ,'C#'
    ,Note.f.sharp.major],
  140:[[Note.g.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.e.sharp.inOctave(3)]
    ,[100.0,'V','6','',]
    ,'C#/E#'
    ,Note.f.sharp.major],
  141:[[Note.e.sharp.inOctave(5)
    ,Note.g.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(3)]
    ,[100.0,'V','4','6',]
    ,'C#/G#'
    ,Note.f.sharp.major],
  142:[[Note.a.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.d.sharp.inOctave(3)]
    ,[100.0,'vi','','',]
    ,'D#m'
    ,Note.f.sharp.major],
  143:[[Note.f.sharp.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.a.sharp.inOctave(3)
    ,Note.f.sharp.inOctave(3)]
    ,[100.0,'vi','6','',]
    ,'D#m/F#'
    ,Note.f.sharp.major],
  144:[[Note.d.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.a.sharp.inOctave(3)]
    ,[100.0,'vi','4','6',]
    ,'D#m/A#'
    ,Note.f.sharp.major],
  145:[[Note.b.inOctave(3)
    ,Note.e.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(3)
    ,Note.e.sharp.inOctave(3)]
    ,[100.0,'vii','','',]
    ,'E#m(5b)'
    ,Note.f.sharp.major],
  146:[[Note.b.inOctave(4)
    ,Note.e.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(3)
    ,Note.g.sharp.inOctave(2)]
    ,[100.0,'vii','6','',]
    ,'E#m(5b)/G#'
    ,Note.f.sharp.major],
  147:[[Note.g.sharp.inOctave(4)
    ,Note.e.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(3)
    ,Note.b.inOctave(2)]
    ,[100.0,'vii','4','6',]
    ,'E#m(5b)/B'
    ,Note.f.sharp.major],
};

Map<int, List<dynamic>> problemListCSharpMajor =
{
  // 문제번호 / 음표위치 / 정답  [-4,7,10,14]
  148:[[Note.e.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(3)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'I','','',]
    ,'C#'
    ,Note.c.sharp.major],
  149:[[Note.g.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.e.sharp.inOctave(3)]
    ,[100.0,'I','6','',]
    ,'C#/E#'
    ,Note.c.sharp.major],
  150:[[Note.e.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(3)
    ,Note.g.sharp.inOctave(2)]
    ,[100.0,'I','4','6',]
    ,'C#/G#'
    ,Note.c.sharp.major],
  151:[[Note.a.sharp.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(3)
    ,Note.d.sharp.inOctave(3)]
    ,[100.0,'ii','','',]
    ,'D#m'
    ,Note.c.sharp.major],
  152:[[Note.a.sharp.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(3)
    ,Note.f.sharp.inOctave(2)]
    ,[100.0,'ii','6','',]
    ,'D#m/F#'
    ,Note.c.sharp.major],
  153:[[Note.f.sharp.inOctave(4)
    ,Note.d.sharp.inOctave(4)
    ,Note.d.sharp.inOctave(3)
    ,Note.a.sharp.inOctave(2)]
    ,[100.0,'ii','4','6',]
    ,'D#m/A#'
    ,Note.c.sharp.major],
  154:[[Note.e.sharp.inOctave(5)
    ,Note.g.sharp.inOctave(4)
    ,Note.b.sharp.inOctave(3)
    ,Note.e.sharp.inOctave(3)]
    ,[100.0,'iii','','',]
    ,'E#m'
    ,Note.c.sharp.major],
  155:[[Note.b.sharp.inOctave(4)
    ,Note.e.sharp.inOctave(4)
    ,Note.e.sharp.inOctave(3)
    ,Note.g.sharp.inOctave(2)]
    ,[100.0,'iii','6','',]
    ,'E#m/G#'
    ,Note.c.sharp.major],
  156:[[Note.e.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(4)
    ,Note.b.sharp.inOctave(3)
    ,Note.b.sharp.inOctave(2)]
    ,[100.0,'iii','4','6',]
    ,'E#m/B#'
    ,Note.c.sharp.major],
  157:[[Note.a.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(3)]
    ,[100.0,'IV','','',]
    ,'F#'
    ,Note.c.sharp.major],
  158:[[Note.c.sharp.inOctave(5)
    ,Note.f.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(3)
    ,Note.a.sharp.inOctave(2)]
    ,[100.0,'IV','6','',]
    ,'F#/A#'
    ,Note.c.sharp.major],
  159:[[Note.a.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'IV','4','6',]
    ,'F#/C#'
    ,Note.c.sharp.major],
  160:[[Note.d.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(4)
    ,Note.b.sharp.inOctave(3)
    ,Note.g.sharp.inOctave(3)]
    ,[100.0,'V','','',]
    ,'G#'
    ,Note.c.sharp.major],
  161:[[Note.d.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(3)
    ,Note.b.sharp.inOctave(2)]
    ,[100.0,'V','6','',]
    ,'G#/B#'
    ,Note.c.sharp.major],
  162:[[Note.d.sharp.inOctave(4)
    ,Note.b.sharp.inOctave(4)
    ,Note.g.sharp.inOctave(3)
    ,Note.d.sharp.inOctave(3)]
    ,[100.0,'V','','',]
    ,'G#/D#'
    ,Note.c.sharp.major],
  163:[[Note.a.sharp.inOctave(4)
    ,Note.e.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.a.sharp.inOctave(3)]
    ,[100.0,'vi','','',]
    ,'A#m'
    ,Note.c.sharp.major],
  164:[[Note.a.sharp.inOctave(4)
    ,Note.e.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(3)]
    ,[100.0,'vi','6','',]
    ,'A#m/C#'
    ,Note.c.sharp.major],
  165:[[Note.a.sharp.inOctave(4)
    ,Note.c.sharp.inOctave(4)
    ,Note.a.sharp.inOctave(3)
    ,Note.e.sharp.inOctave(3)]
    ,[100.0,'vi','4','6',]
    ,'A#m/E#'
    ,Note.c.sharp.major],
  166:[[Note.d.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(3)
    ,Note.b.sharp.inOctave(2)]
    ,[100.0,'vii','','',]
    ,'B#m(5b)'
    ,Note.c.sharp.major],
  167:[[Note.d.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(4)
    ,Note.b.sharp.inOctave(3)
    ,Note.d.sharp.inOctave(3)]
    ,[100.0,'vii','6','',]
    ,'B#m(5b)/D#'
    ,Note.c.sharp.major],
  168:[[Note.d.sharp.inOctave(4)
    ,Note.b.sharp.inOctave(4)
    ,Note.f.sharp.inOctave(3)
    ,Note.f.sharp.inOctave(2)]
    ,[100.0,'vii','4','6',]
    ,'B#m(5b)/F#'
    ,Note.c.sharp.major],
};

Map<int, List<dynamic>> problemListFMajor =
{
  // 문제번호 / 음표위치 / 정답  [-4,7,10,14]
  169:[[Note.a.inOctave(4)
    ,Note.f.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.f.inOctave(3)]
    ,[100.0,'I','','',]
    ,'F'
    ,Note.f.major],
  170:[[Note.c.inOctave(4)
    ,Note.f.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.a.inOctave(2)]
    ,[100.0,'I','6','',]
    ,'F/A'
    ,Note.f.major],
  171:[[Note.c.inOctave(5)
    ,Note.f.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.c.inOctave(3)]
    ,[100.0,'I','4','6',]
    ,'F/C'
    ,Note.f.major],
  172:[[Note.b.flat.inOctave(4)
    ,Note.g.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.g.inOctave(2)]
    ,[100.0,'ii','','',]
    ,'Gm'
    ,Note.f.major],
  173:[[Note.d.inOctave(4)
    ,Note.g.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.b.flat.inOctave(3)]
    ,[100.0,'ii','6','',]
    ,'Gm/Bb'
    ,Note.f.major],
  174:[[Note.b.flat.inOctave(4)
    ,Note.g.inOctave(4)
    ,Note.g.inOctave(3)
    ,Note.d.inOctave(2)]
    ,[100.0,'ii','4','6',]
    ,'Gm/D'
    ,Note.f.major],
  175:[[Note.e.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.a.inOctave(2)]
    ,[100.0,'iii','','',]
    ,'Am'
    ,Note.f.major],
  176:[[Note.e.inOctave(5)
    ,Note.a.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.c.inOctave(3)]
    ,[100.0,'iii','6','',]
    ,'Am/C'
    ,Note.f.major],
  177:[[Note.c.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.e.inOctave(3)]
    ,[100.0,'iii','4','6',]
    ,'Am/E'
    ,Note.f.major],
  178:[[Note.d.inOctave(5)
    ,Note.f.inOctave(4)
    ,Note.b.flat.inOctave(3)
    ,Note.b.flat.inOctave(2)]
    ,[100.0,'IV','','',]
    ,'Bb'
    ,Note.f.major],
  179:[[Note.d.inOctave(4)
    ,Note.f.inOctave(4)
    ,Note.b.flat.inOctave(3)
    ,Note.d.inOctave(3)]
    ,[100.0,'IV','6','',]
    ,'Bb/D'
    ,Note.f.major],
  180:[[Note.b.flat.inOctave(4)
    ,Note.f.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.f.inOctave(3)]
    ,[100.0,'IV','4','6',]
    ,'Bb/F'
    ,Note.f.major],
  181:[[Note.e.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.g.inOctave(3)
    ,Note.c.inOctave(3)]
    ,[100.0,'V','','',]
    ,'C'
    ,Note.f.major],
  182:[[Note.c.inOctave(5)
    ,Note.g.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.e.inOctave(3)]
    ,[100.0,'V','6','',]
    ,'C/E'
    ,Note.f.major],
  183:[[Note.e.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.g.inOctave(3)
    ,Note.g.inOctave(2)]
    ,[100.0,'V','4','6',]
    ,'C/G'
    ,Note.f.major],
  184:[[Note.a.inOctave(4)
    ,Note.f.inOctave(4)
    ,Note.d.inOctave(3)
    ,Note.d.inOctave(2)]
    ,[100.0,'vi','','',]
    ,'Dm'
    ,Note.f.major],
  185:[[Note.a.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.f.inOctave(2)]
    ,[100.0,'vi','6','',]
    ,'Dm/f'
    ,Note.f.major],
  186:[[Note.d.inOctave(4)
    ,Note.f.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.a.inOctave(2)]
    ,[100.0,'vi','4','6',]
    ,'Dm/a'
    ,Note.f.major],
  187:[[Note.b.flat.inOctave(3)
    ,Note.g.inOctave(4)
    ,Note.g.inOctave(3)
    ,Note.e.inOctave(2)]
    ,[100.0,'vii','','',]
    ,'Em(5b)'
    ,Note.f.major],
  188:[[Note.e.inOctave(5)
    ,Note.g.inOctave(4)
    ,Note.b.flat.inOctave(3)
    ,Note.g.inOctave(2)]
    ,[100.0,'vii','6','',]
    ,'Em(5b)/G'
    ,Note.f.major],
  189:[[Note.b.flat.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.g.inOctave(3)
    ,Note.b.flat.inOctave(2)]
    ,[100.0,'vii','4','6',]
    ,'Em(5b)/Bb'
    ,Note.f.major],
    190:[[Note.b.flat.inOctave(4)
      ,Note.d.inOctave(4)
      ,Note.f.inOctave(3)
      ,Note.b.flat.inOctave(2)]
      ,[100.0,'I','','',]
      ,'Bb'
      ,Note.b.flat.major],
    191:[[Note.b.flat.inOctave(4)
      ,Note.f.inOctave(4)
      ,Note.f.inOctave(3)
      ,Note.d.inOctave(3)]
      ,[100.0,'I','6','',]
      ,'Bb/D'
      ,Note.b.flat.major],
    192:[[Note.b.flat.inOctave(4)
      ,Note.d.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.f.inOctave(2)]
      ,[100.0,'I','4','6',]
      ,'Bb/F'
      ,Note.b.flat.major],
    193:[[Note.g.inOctave(4)
      ,Note.e.flat.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.c.inOctave(3)]
      ,[100.0,'ii','','',]
      ,'Cm'
      ,Note.b.flat.major],
    194:[[Note.g.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.e.flat.inOctave(3)]
      ,[100.0,'ii','6','',]
      ,'Cm/Eb'
      ,Note.b.flat.major],
    195:[[Note.g.inOctave(4)
      ,Note.e.flat.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.g.inOctave(3)]
      ,[100.0,'ii','4','6',]
      ,'Cm/G'
      ,Note.b.flat.major],
    196:[[Note.f.inOctave(4)
      ,Note.d.inOctave(4)
      ,Note.a.inOctave(3)
      ,Note.d.inOctave(3)]
      ,[100.0,'iii','','',]
      ,'Dm'
      ,Note.b.flat.major],
    197:[[Note.a.inOctave(4)
      ,Note.d.inOctave(4)
      ,Note.d.inOctave(4)
      ,Note.f.inOctave(3)]
      ,[100.0,'iii','6','',]
      ,'Dm/F'
      ,Note.b.flat.major],
    198:[[Note.f.inOctave(4)
      ,Note.d.inOctave(4)
      ,Note.a.inOctave(3)
      ,Note.a.inOctave(2)]
      ,[100.0,'iii','4','6',]
      ,'Dm/A'
      ,Note.b.flat.major],
    199:[[Note.e.flat.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.g.inOctave(3)
      ,Note.e.flat.inOctave(3)]
      ,[100.0,'IV','','',]
      ,'Eb'
      ,Note.b.flat.major],
    200:[[Note.e.flat.inOctave(4)
      ,Note.b.flat.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.g.inOctave(3)]
      ,[100.0,'IV','6','',]
      ,'Eb/G'
      ,Note.b.flat.major],
    201:[[Note.e.flat.inOctave(4)
      ,Note.b.flat.inOctave(4)
      ,Note.g.inOctave(3)
      ,Note.b.flat.inOctave(2)]
      ,[100.0,'IV','4','6',]
      ,'Eb/Bb'
      ,Note.b.flat.major],
    202:[[Note.a.inOctave(4)
      ,Note.f.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.f.inOctave(3)]
      ,[100.0,'V','','',]
      ,'F'
      ,Note.b.flat.major],
    203:[[Note.f.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.a.inOctave(3)]
      ,[100.0,'V','6','',]
      ,'F/A'
      ,Note.b.flat.major],
    204:[[Note.a.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.f.inOctave(3)
      ,Note.c.inOctave(3)]
      ,[100.0,'V','4','6',]
      ,'F/C'
      ,Note.b.flat.major],
    205:[[Note.g.inOctave(4)
      ,Note.b.flat.inOctave(4)
      ,Note.d.inOctave(4)
      ,Note.g.inOctave(3)]
      ,[100.0,'vi','','',]
      ,'Gm'
      ,Note.b.flat.major],
    206:[[Note.g.inOctave(4)
      ,Note.b.flat.inOctave(4)
      ,Note.d.inOctave(4)
      ,Note.b.flat.inOctave(3)]
      ,[100.0,'vi','6','',]
      ,'Gm/Bb'
      ,Note.b.flat.major],
    207:[[Note.g.inOctave(4)
      ,Note.b.flat.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.d.inOctave(2)]
      ,[100.0,'vi','4','6',]
      ,'Gm/D'
      ,Note.b.flat.major],
    208:[[Note.c.inOctave(4)
      ,Note.e.flat.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.a.inOctave(3)]
      ,[100.0,'vii','','',]
      ,'Am(5b)'
      ,Note.b.flat.major],
    209:[[Note.c.inOctave(5)
      ,Note.e.flat.inOctave(4)
      ,Note.a.inOctave(3)
      ,Note.c.inOctave(3)]
      ,[100.0,'vii','6','',]
      ,'Am(5b)/C'
      ,Note.b.flat.major],
    210:[[Note.c.inOctave(4)
      ,Note.a.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.e.flat.inOctave(3)]
      ,[100.0,'vii','4','6',]
      ,'Am(5b)/Eb'
      ,Note.b.flat.major],
    211:[[Note.b.flat.inOctave(4)
      ,Note.g.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.e.flat.inOctave(3)]
      ,[100.0,'I','','',]
      ,'Eb'
      ,Note.e.flat.major],
    212:[[Note.b.flat.inOctave(4)
      ,Note.e.flat.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.g.inOctave(3)]
      ,[100.0,'I','6','',]
      ,'Eb/G'
      ,Note.e.flat.major],
    213:[[Note.e.flat.inOctave(5)
      ,Note.g.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.b.flat.inOctave(2)]
      ,[100.0,'I','4','6',]
      ,'Eb/Bb'
      ,Note.e.flat.major],
    214:[[Note.f.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.a.flat.inOctave(3)
      ,Note.f.inOctave(2)]
      ,[100.0,'ii','','',]
      ,'Fm'
      ,Note.e.flat.major],
    215:[[Note.f.inOctave(4)
      ,Note.c.inOctave(5)
      ,Note.a.flat.inOctave(3)
      ,Note.a.flat.inOctave(2)]
      ,[100.0,'ii','6','',]
      ,'Fm/Ab'
      ,Note.e.flat.major],
    216:[[Note.f.inOctave(4)
      ,Note.a.flat.inOctave(4)
      ,Note.a.flat.inOctave(3)
      ,Note.c.inOctave(3)]
      ,[100.0,'ii','4','6',]
      ,'Fm/C'
      ,Note.e.flat.major],
    217:[[Note.g.inOctave(4)
      ,Note.d.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.g.inOctave(2)]
      ,[100.0,'iii','','',]
      ,'Gm'
      ,Note.e.flat.major],
    218:[[Note.g.inOctave(4)
      ,Note.d.inOctave(5)
      ,Note.b.flat.inOctave(3)
      ,Note.b.flat.inOctave(2)]
      ,[100.0,'iii','6','',]
      ,'Gm/Bb'
      ,Note.e.flat.major],
    219:[[Note.g.inOctave(4)
      ,Note.d.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.d.inOctave(2)]
      ,[100.0,'iii','4','6',]
      ,'Gm/D'
      ,Note.e.flat.major],
    220:[[Note.a.flat.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.e.flat.inOctave(3)
      ,Note.a.flat.inOctave(2)]
      ,[100.0,'IV','','',]
      ,'Ab'
      ,Note.e.flat.major],
    221:[[Note.e.flat.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.a.flat.inOctave(3)
      ,Note.c.inOctave(3)]
      ,[100.0,'IV','6','',]
      ,'Ab/C'
      ,Note.e.flat.major],
    222:[[Note.a.flat.inOctave(4)
      ,Note.c.inOctave(5)
      ,Note.c.inOctave(4)
      ,Note.e.flat.inOctave(3)]
      ,[100.0,'IV','4','6',]
      ,'Ab/Eb'
      ,Note.e.flat.major],
    223:[[Note.f.inOctave(4)
      ,Note.d.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.b.flat.inOctave(2)]
      ,[100.0,'V','','',]
      ,'Bb'
      ,Note.e.flat.major],
    224:[[Note.f.inOctave(5)
      ,Note.f.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.d.inOctave(2)]
      ,[100.0,'V','6','',]
      ,'Bb/D'
      ,Note.e.flat.major],
    225:[[Note.f.inOctave(4)
      ,Note.d.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.f.inOctave(2)]
      ,[100.0,'V','4','6',]
      ,'Bb/F'
      ,Note.e.flat.major],
    226:[[Note.e.flat.inOctave(5)
      ,Note.e.flat.inOctave(4)
      ,Note.g.inOctave(3)
      ,Note.c.inOctave(3)]
      ,[100.0,'vi','','',]
      ,'Cm'
      ,Note.e.flat.major],
    227:[[Note.g.inOctave(4)
      ,Note.e.flat.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.e.flat.inOctave(3)]
      ,[100.0,'vi','6','',]
      ,'Cm/Eb'
      ,Note.e.flat.major],
    228:[[Note.c.inOctave(5)
      ,Note.e.flat.inOctave(4)
      ,Note.g.inOctave(3)
      ,Note.g.inOctave(2)]
      ,[100.0,'vi','4','6',]
      ,'Cm/G'
      ,Note.e.flat.major],
    229:[[Note.f.inOctave(5)
      ,Note.f.inOctave(4)
      ,Note.a.flat.inOctave(3)
      ,Note.d.inOctave(3)]
      ,[100.0,'vii','','',]
      ,'Dm(5b)'
      ,Note.e.flat.major],
    230:[[Note.d.inOctave(5)
      ,Note.f.inOctave(4)
      ,Note.a.flat.inOctave(3)
      ,Note.f.inOctave(3)]
      ,[100.0,'vii','6','',]
      ,'Dm(5b)/F'
      ,Note.e.flat.major],
    231:[[Note.f.inOctave(5)
      ,Note.f.inOctave(4)
      ,Note.d.inOctave(4)
      ,Note.a.flat.inOctave(2)]
      ,[100.0,'vii','4','6',]
      ,'Dm(5b)/Ab'
      ,Note.e.flat.major],
    232:[[Note.e.flat.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.a.flat.inOctave(3)
      ,Note.a.flat.inOctave(2)]
      ,[100.0,'I','','',]
      ,'Ab'
      ,Note.a.flat.major],
    233:[[Note.e.flat.inOctave(5)
      ,Note.e.flat.inOctave(4)
      ,Note.a.flat.inOctave(3)
      ,Note.c.inOctave(3)]
      ,[100.0,'I','6','',]
      ,'Ab/C'
      ,Note.a.flat.major],
    234:[[Note.a.flat.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.a.flat.inOctave(3)
      ,Note.e.flat.inOctave(2)]
      ,[100.0,'I','4','6',]
      ,'Ab/Eb'
      ,Note.a.flat.major],
    235:[[Note.f.inOctave(4)
      ,Note.d.flat.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.b.flat.inOctave(2)]
      ,[100.0,'ii','','',]
      ,'Bbm'
      ,Note.a.flat.major],
    236:[[Note.f.inOctave(4)
      ,Note.b.flat.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.d.flat.inOctave(2)]
      ,[100.0,'ii','6','',]
      ,'Bbm/Db'
      ,Note.a.flat.major],
    237:[[Note.f.inOctave(4)
      ,Note.d.flat.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.f.inOctave(2)]
      ,[100.0,'ii','4','6',]
      ,'Bbm/F'
      ,Note.a.flat.major],
    238:[[Note.c.inOctave(5)
      ,Note.e.flat.inOctave(4)
      ,Note.g.inOctave(3)
      ,Note.c.inOctave(3)]
      ,[100.0,'iii','','',]
      ,'Cm'
      ,Note.a.flat.major],
    239:[[Note.g.inOctave(4)
      ,Note.e.flat.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.e.flat.inOctave(2)]
      ,[100.0,'iii','6','',]
      ,'Cm/Eb'
      ,Note.a.flat.major],
    240:[[Note.c.inOctave(5)
      ,Note.e.flat.inOctave(4)
      ,Note.g.inOctave(3)
      ,Note.g.inOctave(2)]
      ,[100.0,'iii','4','6',]
      ,'Cm/G'
      ,Note.a.flat.major],
    241:[[Note.a.flat.inOctave(4)
      ,Note.d.flat.inOctave(4)
      ,Note.f.inOctave(3)
      ,Note.d.flat.inOctave(3)]
      ,[100.0,'IV','','',]
      ,'Db'
      ,Note.a.flat.major],
    242:[[Note.a.flat.inOctave(4)
      ,Note.d.flat.inOctave(4)
      ,Note.a.flat.inOctave(3)
      ,Note.f.inOctave(3)]
      ,[100.0,'IV','6','',]
      ,'Db/F'
      ,Note.a.flat.major],
    243:[[Note.a.flat.inOctave(4)
      ,Note.f.inOctave(4)
      ,Note.d.flat.inOctave(4)
      ,Note.a.flat.inOctave(2)]
      ,[100.0,'IV','4','6',]
      ,'Db/Ab'
      ,Note.a.flat.major],
    244:[[Note.e.flat.inOctave(4)
      ,Note.b.flat.inOctave(4)
      ,Note.g.inOctave(3)
      ,Note.e.flat.inOctave(3)]
      ,[100.0,'V','','',]
      ,'Eb'
      ,Note.a.flat.major],
    245:[[Note.e.flat.inOctave(5)
      ,Note.e.flat.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.g.inOctave(3)]
      ,[100.0,'V','6','',]
      ,'Eb/G'
      ,Note.a.flat.major],
    246:[[Note.e.flat.inOctave(4)
      ,Note.b.flat.inOctave(3)
      ,Note.g.inOctave(3)
      ,Note.b.flat.inOctave(2)]
      ,[100.0,'V','4','6',]
      ,'Eb/Bb'
      ,Note.a.flat.major],
    247:[[Note.f.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.a.flat.inOctave(3)
      ,Note.f.inOctave(3)]
      ,[100.0,'vi','','',]
      ,'Fm'
      ,Note.a.flat.major],
    248:[[Note.f.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.a.flat.inOctave(3)
      ,Note.a.flat.inOctave(2)]
      ,[100.0,'vi','6','',]
      ,'Fm/Ab'
      ,Note.a.flat.major],
    249:[[Note.a.flat.inOctave(4)
      ,Note.c.inOctave(4)
      ,Note.f.inOctave(3)
      ,Note.c.inOctave(3)]
      ,[100.0,'vi','4','6',]
      ,'Fm/C'
      ,Note.a.flat.major],
    250:[[Note.b.flat.inOctave(4)
      ,Note.d.flat.inOctave(4)
      ,Note.d.flat.inOctave(4)
      ,Note.g.inOctave(3)]
      ,[100.0,'vii','','',]
      ,'Gm(5b)'
      ,Note.a.flat.major],
    251:[[Note.b.flat.inOctave(4)
      ,Note.g.inOctave(4)
      ,Note.d.flat.inOctave(4)
      ,Note.b.flat.inOctave(3)]
      ,[100.0,'vii','6','',]
      ,'Gm(5b)/Bb'
      ,Note.a.flat.major],
  252:[[Note.b.flat.inOctave(4)
    ,Note.d.flat.inOctave(4)
    ,Note.g.inOctave(3)
    ,Note.d.flat.inOctave(3)]
    ,[100.0,'vii','4','6',]
    ,'Gm(5b)/Db'
    ,Note.a.flat.major],
};
