import '../problemFunc/problemFuncHarmony.dart';
import 'package:music_notes/music_notes.dart';


Map<int, List<List<dynamic>>> problemType1List =
{
  // 문제번호 / 음표위치 / 정답  [-4,7,10,14]
  1:[[Note.e.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.g.inOctave(3)
    ,Note.c.inOctave(3)]
    ,[100.0,'I','',''],],
  2:[[Note.c.inOctave(5)
    ,Note.g.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.e.inOctave(3)]
    ,[100.0,'I','6','',],],
  3:[[Note.e.inOctave(5)
    ,Note.g.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.g.inOctave(3)]
    ,[100.0,'I','4','6',],],
  4:[[Note.a.inOctave(4)
    ,Note.f.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.d.inOctave(3)]
    ,[100.0,'ii','','',],],
  5:[[Note.d.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.f.inOctave(3)]
    ,[100.0,'ii','6','',],],
  6:[[Note.d.inOctave(5)
    ,Note.f.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.a.inOctave(3)]
    ,[100.0,'ii','4','6',],],
  7:[[Note.b.inOctave(4)
    ,Note.g.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.e.inOctave(3)]
    ,[100.0,'iii','','',],],
  8:[[Note.b.inOctave(4)
    ,Note.g.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.g.inOctave(3)]
    ,[100.0,'iii','6','',],],
  9:[[Note.b.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.g.inOctave(3)
    ,Note.b.inOctave(2)]
    ,[100.0,'iii','4','6',],],
  10:[[Note.f.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.f.inOctave(2)]
    ,[100.0,'IV','','',],],
  11:[[Note.c.inOctave(4)
    ,Note.f.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.a.inOctave(3)]
    ,[100.0,'IV','6','',],],
  12:[[Note.f.inOctave(5)
    ,Note.a.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.c.inOctave(3)]
    ,[100.0,'IV','4','6',],],
  13:[[Note.b.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.g.inOctave(3)
    ,Note.g.inOctave(2)]
    ,[100.0,'V','','',],],
  14:[[Note.b.inOctave(4)
    ,Note.g.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.b.inOctave(2)]
    ,[100.0,'V','6','',],],
  15:[[Note.g.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.d.inOctave(3)]
    ,[100.0,'V','4','6',],],
  16:[[Note.a.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.e.inOctave(3)
    ,Note.a.inOctave(2)]
    ,[100.0,'vi','','',],],
  17:[[Note.e.inOctave(4)
    ,Note.a.inOctave(4)
    ,Note.c.inOctave(4)
    ,Note.c.inOctave(3)]
    ,[100.0,'vi','6','',],],
  18:[[Note.c.inOctave(4)
    ,Note.e.inOctave(4)
    ,Note.a.inOctave(3)
    ,Note.e.inOctave(2)]
    ,[100.0,'vi','4','6',],],
  19:[[Note.d.inOctave(4)
    ,Note.f.inOctave(4)
    ,Note.d.inOctave(4)
    ,Note.b.inOctave(2)]
    ,[100.0,'vii','','',],],
  20:[[Note.d.inOctave(4)
    ,Note.b.inOctave(4)
    ,Note.f.inOctave(3)
    ,Note.d.inOctave(3)]
    ,[100.0,'vii','6','',],],
  21:[[Note.d.inOctave(5)
    ,Note.d.inOctave(4)
    ,Note.b.inOctave(3)
    ,Note.f.inOctave(3)]
    ,[100.0,'vii','4','6',],],
};
